// AN.Audio.BindingsCompiler — build-only tool (spec 71). Same two commands as FluidUI's compilers:
//
//   extract   <wanted.hjson> <declarations.hjson> <report.json> [--sdk-root <dir>]
//             Explicit refresh, developer-run, needs the SDK on disk. Writes the report ALWAYS, the declarations only when
//             every wanted item was found exactly once and no preprocessor/parse error occurred (nonzero exit otherwise;
//             the previous declarations file is left untouched).
//
//   normalize <declarations.hjson> <renderModel.hjson>
//             Ordinary build. Validates the committed declarations and derives the render model the YeetCode templates consume
//             (C# names, ABI layouts for every declared ABI, vtable slots, delegate* signatures).
//
// The runtime library never links this assembly.
namespace AN.Audio.BindingsCompiler;

public static class BindingsCompiler_Program
{
    private const int ExitCode_Ok = 0;
    private const int ExitCode_UsageError = 64;        // EX_USAGE
    private const int ExitCode_ExtractionFailed = 65;  // EX_DATAERR

    public static int Main(string[] args)
    {
        if (args.Length == 0) return PrintUsage("missing command");
        return args[0] switch
        {
            "extract" => RunExtract(args[1..]),
            "normalize" => RunNormalize(args[1..]),
            "--help" or "-h" or "help" => PrintUsage(null),
            _ => PrintUsage($"unknown command '{args[0]}'"),
        };
    }

    private static int RunExtract(string[] a)
    {
        string? sdkRoot = null;
        var positional = new List<string>();
        for (int i = 0; i < a.Length; i++)
        {
            if (a[i] == "--sdk-root" && i + 1 < a.Length) sdkRoot = a[++i];
            else positional.Add(a[i]);
        }
        if (positional.Count != 3) return PrintUsage("extract expects: <wanted.hjson> <declarations.hjson> <report.json> [--sdk-root <dir>]");
        string wantedPath = positional[0], declarationsPath = positional[1], reportPath = positional[2];
        if (!File.Exists(wantedPath)) { Console.Error.WriteLine($"extract: not found: {wantedPath}"); return ExitCode_UsageError; }

        CHeader_Extractor.ExtractionResult result;
        try { result = CHeader_Extractor.Extract(wantedPath, sdkRoot); }
        catch (InvalidDataException e) { Console.Error.WriteLine($"extract: {e.Message}"); return ExitCode_ExtractionFailed; }

        CHeader_Extractor.WriteFileAtomically(reportPath, System.Text.Json.JsonSerializer.Serialize(result.Report, CHeader_Extractor.JsonOptions) + "\n");
        foreach (string w in result.Report.Warnings) Console.Error.WriteLine($"extract: warning: {w}");
        foreach (string e in result.Report.Errors) Console.Error.WriteLine($"extract: error: {e}");
        if (!result.Succeeded)
        {
            Console.Error.WriteLine($"extract: FAILED ({result.Report.Errors.Count} error(s)); declarations NOT written, report at {reportPath}");
            return ExitCode_ExtractionFailed;
        }
        string json = System.Text.Json.JsonSerializer.Serialize(result.Declarations, CHeader_Extractor.JsonOptions);
        CHeader_Extractor.WriteFileAtomically(declarationsPath,
            "// GENERATED by `AN.Audio.BindingsCompiler extract` from the SDK headers named in Wanted.ytdata.hjson (spec 71). DO NOT EDIT — re-run extract.\n" + json + "\n");
        var d = result.Declarations!;
        Console.WriteLine($"extract: OK — {d.Surfaces.Count} surface(s), {d.Surfaces.Sum(s => s.Typedefs.Count)} typedef(s), {d.Surfaces.Sum(s => s.Structs.Count)} struct(s), {d.Surfaces.Sum(s => s.Enums.Count)} enum(s), {d.Surfaces.Sum(s => s.Classes.Count)} class(es) → {declarationsPath}");
        return ExitCode_Ok;
    }

    private static int RunNormalize(string[] a)
    {
        if (a.Length != 2) return PrintUsage("normalize expects: <declarations.hjson> <renderModel.hjson>");
        if (!File.Exists(a[0])) { Console.Error.WriteLine($"normalize: not found: {a[0]}"); return ExitCode_UsageError; }
        try
        {
            string json = CHeader_DeclarationCompiler.NormalizeHjsonToJson(File.ReadAllText(a[0]), a[0]);
            CHeader_Extractor.WriteFileAtomically(a[1], json);
            Console.WriteLine($"normalize: OK → {a[1]}");
            return ExitCode_Ok;
        }
        catch (InvalidDataException e)
        {
            Console.Error.WriteLine($"normalize: {e.Message}");
            return ExitCode_ExtractionFailed;
        }
    }

    private static int PrintUsage(string? error)
    {
        TextWriter o = error is null ? Console.Out : Console.Error;
        if (error is not null) o.WriteLine($"error: {error}");
        o.WriteLine("AN.Audio.BindingsCompiler (spec 71)");
        o.WriteLine("  extract   <wanted.hjson> <declarations.hjson> <report.json> [--sdk-root <dir>]");
        o.WriteLine("  normalize <declarations.hjson> <renderModel.hjson>");
        return error is null ? ExitCode_Ok : ExitCode_UsageError;
    }
}