#!/usr/bin/env pwsh
# gen-version-file.ps1 — Generate AN.Audio.Version.generated.props from version.jsonc + git
#
# Reads version.jsonc (base version + buildNumberOffset) and git info,
# writes a static .props file that MSBuild imports for all projects.
# This file is gitignored — regenerate after clone or version bump.
#
# Usage:
#   ./cmd/gen-version-file.ps1              # generate from current version.jsonc
#   ./cmd/gen-version-file.ps1 -Prerelease  # include prerelease suffix in PackageVersion

param(
    [switch]$Prerelease
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$versionJsoncPath = Join-Path $repoRoot "version.jsonc"
$outputPropsPath = Join-Path $repoRoot "AN.Audio.Version.generated.props"

# Locate JsonPeek.exe from ArtificialNecessity.CodeAnalyzers package
$packageBase = Join-Path $env:USERPROFILE ".nuget\packages\artificialnecessity.codeanalyzers"
if (-not (Test-Path $packageBase)) {
    Write-Host "ERROR: Package artificialnecessity.codeanalyzers not found in NuGet cache." -ForegroundColor Red
    Write-Host "Run 'dotnet restore' first to ensure ArtificialNecessity.CodeAnalyzers is installed." -ForegroundColor Yellow
    exit 1
}
$latestVersion = Get-ChildItem $packageBase -Directory |
    Where-Object { $_.Name -notmatch '-' } |
    Sort-Object { [version]$_.Name } |
    Select-Object -Last 1
if (-not $latestVersion) { Write-Host "ERROR: No stable version of artificialnecessity.codeanalyzers found." -ForegroundColor Red; exit 1 }
$jsonPeekExePath = Join-Path $latestVersion.FullName "tools\net8.0\any\JsonPeek.exe"
if (-not (Test-Path $jsonPeekExePath)) {
    Write-Host "ERROR: JsonPeek.exe not found at $jsonPeekExePath" -ForegroundColor Red
    Write-Host "Expected it inside package version $($latestVersion.Name)" -ForegroundColor Yellow
    exit 1
}

# Read version.jsonc
$baseVersion = & $jsonPeekExePath $versionJsoncPath version
if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: Failed to read 'version' from $versionJsoncPath" -ForegroundColor Red; exit 1 }

$buildNumberOffset = & $jsonPeekExePath $versionJsoncPath buildNumberOffset
if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: Failed to read 'buildNumberOffset' from $versionJsoncPath" -ForegroundColor Red; exit 1 }

$versionPrefix = "$baseVersion.$buildNumberOffset"

# Git info
$gitCommitHeight = (git rev-list --count HEAD).Trim()
$gitShortHash = (git rev-parse --short HEAD).Trim()

$informationalVersion = "$versionPrefix+$gitCommitHeight.g$gitShortHash"

# Write the .props file
$propsContent = @"
<!-- AUTO-GENERATED by cmd/gen-version-file.ps1 — do not edit manually -->
<!-- Regenerate: ./cmd/gen-version-file.ps1 -->
<Project>
  <PropertyGroup>
    <VersionPrefix>$versionPrefix</VersionPrefix>
    <Version>$versionPrefix</Version>
    <AssemblyVersion>$versionPrefix.0</AssemblyVersion>
    <FileVersion>$versionPrefix.0</FileVersion>
    <InformationalVersion>$informationalVersion</InformationalVersion>
    <GitCommitHeight>$gitCommitHeight</GitCommitHeight>
    <GitShortHash>$gitShortHash</GitShortHash>
  </PropertyGroup>
</Project>
"@

Set-Content -Path $outputPropsPath -Value $propsContent -Encoding UTF8
Write-Host "Generated $outputPropsPath" -ForegroundColor Green
Write-Host "  Version:              $versionPrefix" -ForegroundColor Cyan
Write-Host "  AssemblyVersion:      $versionPrefix.0" -ForegroundColor Cyan
Write-Host "  InformationalVersion: $informationalVersion" -ForegroundColor Cyan